import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "../components/Providers";
import ClickSpark from "../components/ClickSpark";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="relative overflow-x-hidden ${geistSans.variable} ${geistMono.variable} antialiased">
        {/* background */}
        <div className="absolute inset-0 -z-10">

        </div>

        <ClickSpark>
          <Providers>{children}</Providers>
        </ClickSpark>
      </body>
    </html>
  );
}
